### ISSUE TITLE
Make UI more informative

### ISSUE THREAD

**Issue by berggren** [google/timesketch#124]
Tracking the following issues:
- [ ] #118 Make underlying index identifier visible in the UI 
- [ ] #117 Add additional metadata to "Add Timeline to sketch" 
- [ ] #109 Show sketch status / owner on the main page
- [ ] #127 Hide timed out psort tasks
