### ISSUE TITLE
UI next gen MVP roadmap

### ISSUE THREAD

**Issue by berggren** [google/timesketch#2193]
**Home page (sketch list)**
- [x] #2475
- [x] #2476
- [x] #2477
- [x] #2478

**Home (overview)**
- [x] Generic info page as placeholder until Scenarios take off
- [x] Title
- [x] #2479
- [x] List of timelines
- [x] List of saved searches

**Explore**
- [x] #2481
- [x] #2482
- [x] #2483
- [x] #2484
- [x] #2485
- [x] #2486
- [x] #2487
- [x] #2488
- [x] #2489
- [x] Make bubbles smaller
- [x] Move "Add filter" button
- [x] #2490
- [x] #2491
- [x] #2492
- [x] #2493

**Login**
- [x] #2494

**Graph**
- [x] Port over as full page
- [x] Redesign landing page
- [x] Move filters to left panel

**Automation** (analyzers)
- [x] Port over as is for now

**Intelligence**
- [x] Port over as simple table view

**Comment by jaegeral** [comment]
For explore:

- [ ] Copy event / attribute

**Comment by jaegeral** [comment]
https://github.com/google/timesketch/pull/2119
https://github.com/google/timesketch/pull/2286
https://github.com/google/timesketch/pull/2282
https://github.com/google/timesketch/pull/2281
https://github.com/google/timesketch/pull/2119

**Comment by berggren** [comment]
This has completed.
