### ISSUE TITLE
Refactor the JS frontend code

### ISSUE THREAD

**Issue by berggren** [google/timesketch#46]
## Refactor the JS frontend code
The current structure of the frontend JS code is hard to test and is somewhat confusing, e.g mixing server-side templates with client-side templates. In order to make this better we need to refactor the code.

#### Sub tasks
- [x] #61 - Move REST API calls to services
- [x] #66 - Move controllers to directives
- [x] #67 - Utilize templateURL for directives

See this old PR and comments as starting points: https://github.com/google/timesketch/pull/45

**Comment by berggren** [comment]
This is done.
